version = 0.1

[dev]
parameter_overrides = [
  "HostedZoneId=Z05558683FC949RPHCKBP",
  "DomainName=wealth.dorsay.dev",
  "Environment=dev"
]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "wealth-for-ynab-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9hep6u2wm2mb"
s3_prefix = "wealth-for-ynab-dev"
fail_on_empty_changeset = false
image_repositories = [
  "Logout=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/logout",
  "VerifySession=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/verify",
  "YnabLogin=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/login",
  "YnabToken=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/token",
  "YnabGetBudgets=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/get-budgets",
  "YnabGetAccounts=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/get-accounts",
  "YnabGetNetWorth=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/get-net-worth",
  "YnabGetNetWorthForAccount=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/ynab/get-net-worth-for-account",
  "Forecast=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/dev/forecast"
]




[prod]
parameter_overrides = [
  "HostedZoneId=Z04959741ZMYR4OI07S2",
  "DomainName=wealthforynab.com",
  "Environment=prod"
]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "wealth-for-ynab-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9hep6u2wm2mb"
s3_prefix = "wealth-for-ynab-prod"
fail_on_empty_changeset = false
image_repositories = [
  "Logout=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/logout",
  "VerifySession=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/verify",
  "YnabLogin=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/login",
  "YnabToken=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/token",
  "YnabGetBudgets=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/get-budgets",
  "YnabGetAccounts=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/get-accounts",
  "YnabGetNetWorth=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/get-net-worth",
  "YnabGetNetWorthForAccount=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/ynab/get-net-worth-for-account",
  "Forecast=241743836035.dkr.ecr.us-east-1.amazonaws.com/wealth/prod/forecast"
]
