AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Wealth for YNAB

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 50
            Period: DAY
          Throttle:
            BurstLimit: 100
            RateLimit: 50

  Login:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src
      Dockerfile: auth/Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: login
        SERVICE_NAME: auth
    Properties:
      PackageType: Image
      ImageUri: login:v1
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: YNAB/*
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/login
            Method: GET

  Logout:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: logout
        SERVICE_NAME: auth
    Properties:
      PackageType: Image
      ImageUri: logout:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: Api
            Path: /auth/logout
            Method: GET

  Token:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/auth
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: token
        SERVICE_NAME: auth
    Properties:
      PackageType: Image
      ImageUri: token:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: Api
            Path: /auth/token
            Method: GET

  Forecast:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: python8fbforecast
      DockerContext: src/forecast
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      ImageUri: forecast:python8fbforecast
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: Api
            Path: /forecast
            Method: POST

  SessionStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SessionStore
      AttributeDefinitions:
        - AttributeName: User
          AttributeType: "S"
        - AttributeName: AccessToken
          AttributeType: "S"
        - AttributeName: RefreshToken
          AttributeType: "S"
        - AttributeName: ExpiresIn
          AttributeType: "N"
      KeySchema:
        - AttributeName: User
          KeyType: HASH

      

Outputs:
  ApiUrl:
    Description: API Endpoint
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod"
