AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Wealth for YNAB

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 50
            Period: DAY
          Throttle:
            BurstLimit: 100
            RateLimit: 50

  Forecast:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: python8fbforecast
      DockerContext: src/forecast
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      ImageUri: forecast:python8fbforecast
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: Api
            Path: /forecast
            Method: POST
      

Outputs:
  ApiUrl:
    Description: API Endpoint
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod"
