AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Wealth for YNAB

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: false
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 50
            Period: DAY
          Throttle:
            BurstLimit: 100
            RateLimit: 50

  Logout:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      DockerBuildArgs:
        FUNCTION_NAME: logout
        FUNCTION_SCOPE: other
    Properties:
      PackageType: Image
      ImageUri: logout:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/logout
            Method: GET

  # YNAB
  YnabLogin:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      DockerBuildArgs:
        FUNCTION_NAME: login
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: login:v1
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: YNAB/*
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/login
            Method: GET

  YnabToken:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      DockerBuildArgs:
        FUNCTION_NAME: token
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: token:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /auth/token
            Method: GET

  YnabGetBudgets:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: getBudgets
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: getbudgets:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /ynab/budgets
            Method: GET

  YnabGetAccounts:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: getAccounts
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: getaccounts:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /ynab/budgets/{budget_id}/accounts
            Method: GET

  YnabGetMonthlyNetWorth:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: getMonthlyNetWorth
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: getmonthlynetworth:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /ynab/budgets/:budget_id/monthlyNetWorth
            Method: GET

  YnabGetMonthlyNetWorthForAccount:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: getMonthlyNetWorthForAccount
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: getmonthlynetworthforaccount:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /ynab/budgets/{budget_id}/accounts/{account_id}/monthlyNetWorth
            Method: GET

  YnabGetDailyNetWorth:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/main
      Dockerfile: Dockerfile
      DockerBuildArgs:
        FUNCTION_NAME: getDailyNetWorth
        FUNCTION_SCOPE: ynab
    Properties:
      PackageType: Image
      ImageUri: getdailynetworth:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /ynab/budgets/:budget_id/dailyNetWorth
            Method: GET

  Forecast:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: v1
      DockerContext: src/forecast
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      ImageUri: forecast:v1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /forecast
            Method: GET

  SessionStore:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Sessions
      AttributeDefinitions:
        - AttributeName: HashKey
          AttributeType: "S"
        - AttributeName: RangeKey
          AttributeType: "S"
      KeySchema:
        - AttributeName: HashKey
          KeyType: HASH
        - AttributeName: RangeKey
          KeyType: RANGE

      

Outputs:
  ApiUrl:
    Description: API Endpoint
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod"
