#!/usr/bin/env bash

FUNCTION_NAME=$1
FUNCTION_SCOPE=$2

./scripts/build-docker $FUNCTION_NAME $FUNCTION_SCOPE
containerId=$(./scripts/run-docker $FUNCTION_NAME $FUNCTION_SCOPE)

echo -e "\nRequest response:\n"
./scripts/invoke $FUNCTION_SCOPE-$FUNCTION_NAME | node_modules/node-jq/bin/jq '.'

echo -e "\n\nDocker logs:\n"
docker logs $containerId

echo -e "\nStopping container"
docker stop $containerId
