name: Build

on:
  push:
    branches:
      - aws-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SAM Validate
        run: |
          sam validate
