name: Build Web

on:
  push:
    branches:
      - master
    paths:
      - web/**
      - .github/workflows/build-web.yml

env:
  BUCKET_NAME: todo
  DISTRIBUTION_ID: Z04959741ZMYR4OI07S2
  
defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          aws s3 sync --cache-control 'max-age=604800' --exclude index.html dist s3://$BUCKET_NAME
          aws s3 sync --cache-control 'no-cache' dist s3://$BUCKET_NAME
          aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION_ID --paths /*
